stages:
  - test
  - build
  - release

variables:
  SERVICE_NAME: chat-client-web
  DOCKER_IMAGE: "gcr.io/help-1272/${SERVICE_NAME}:latest"

test:unit:
  image: gcr.io/help-1272/golang:1.6
  stage: test
  script:
    - mkdir -p /go/src/git.help.com/helpdotcom/goose
    - cp -R /builds/helpdotcom/goose/* /go/src/git.help.com/helpdotcom/goose
    - cd /go/src/git.help.com/helpdotcom/goose
    - make clean
    - make test


deploy_bundle_to_staging:
  image: gcr.io/help-1272/golang:1.6
  stage: release
  script:
    - mkdir -p /go/src/git.help.com/helpdotcom/goose
    - cp -R /builds/helpdotcom/goose/* /go/src/git.help.com/helpdotcom/goose
    - cd /go/src/git.help.com/helpdotcom/goose
    - make clean
    - make
    - touch ~/google_cloud_storage_key.json
    - echo ${GOOGLE_CLOUD_STORAGE_PASSWORD} > ~/google_cloud_storage_key.json
    - gcloud auth activate-service-account --key-file ~/google_cloud_storage_key.json
    - gsutil cp /go/src/git.help.com/helpdotcom/goose/cmd/goose/goose gs://helpdotcom-binaries
  only:
    - master
