version: '2'
services:
  goose:
    build:
      context: ../
    command: bash -c "sleep 15 && goose up && /go/src/github.com/cryptowalkio/goose/test/migration_test.bash"
    depends_on:
      - postgresql-db

  postgresql-db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "abcd1234"
      POSTGRES_DB: "database"
